### Installation of SQL-Database ###

- name: install packages
  shell:
    sudo apt install -y mariadb-server python3-pymysql

- name: 
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch

- name: edit the configuration file
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: present
    line: "{{ item }}"
  with_items:
  - [mysql]
  - bind-address = 10.0.0.11
  - |
  - default-storage-engine = innodb
  - innodb_file_per_table = on
  - max_connections = 4096
  - collation-server = utf_general_ci

- name: restart the database service
  shell:
    service mysql restart

- name: secure the database service
  expect:
    command: mysql_secure_installation
    responses:
     ' Enter current password fot the root': ''
     ' Set root password': 'n'
     ' Remove anonymous users': 'y'
     ' disallow root login remotely': 'y'
     ' Remove test database': 'y'
     ' Replace privilege tables now': 'y'
    timeout:
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb.stdout_lines"
