### Installation of Message-Queue ###

- name: install the package
  shell:
    sudo apt install -y rabbitmq-server

- name: Add the OpenStack user to RabbitMQ
  community.rabbitmq.rabbitmq_user:
    user: ma_localmachine
    password: RABBIT_AJK
    state: present
  become: true

- name: Set permissions for RabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: ma_localmachine
    permissions:
      configure: ".*"
      write: ".*"
      read: ".*"
    state: present
  become: true

